const express = require("express");
const {
  getContacts,   
  createContact,
  updateContact,
  deleteContact,
  getContactById 
} = require("../controllers/contactController");
const router = express.Router();

/**
 * @swagger
 * components:
 *   schemas:
 *     Contact: 
 *       type: object
 *       required:
 *         - firstName
 *         - lastName
 *         - email
 *         - favoriteColor
 *       properties:
 *         id: 
 *           type: string
 *           description: The auto-generated MongoDB ID
 *         firstName:
 *           type: string
 *           description: The contact's first name
 *         lastName:
 *           type: string
 *           description: The contact's last name
 *         email:
 *           type: string
 *           format: email
 *           description: The contact's unique email address
 *         favoriteColor:
 *           type: string
 *           description: The contact's favorite color
 *       example:
 *         id: 60d0fe4f5311236168a109ca 
 *         firstName: Jane
 *         lastName: Doe
 *         email: jane.doe@example.com
 *         favoriteColor: blue
 */

/**
 * @swagger
 * /api/contacts:
 *   get:
 *     summary: Get all contacts
 *     tags: [Contacts] 
 *     responses:
 *       200:
 *         description: A list of contacts
 *         content:
 *           application/json:
 *             schema:
 *               type: array
 *               items:
 *                 $ref: '#/components/schemas/Contact' 
 *       500:
 *          description: Error fetching contacts
 */

router.get("/contacts", getContacts);

/**
 * @swagger
 * /api/contacts/{id}: 
 *   get:
 *     summary: Get a single contact by ID
 *     tags: [Contacts]
 *     parameters:
 *       - in: path
 *         name: id
 *         schema:
 *           type: string
 *         required: true
 *         description: The contact ID
 *     responses:
 *       200:
 *         description: The requested contact details
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/Contact'
 *       400:
 *         description: Invalid ID format
 *       404:
 *         description: Contact not found
 *       500:
 *         description: Error fetching contact
 */

router.get("/contacts/:id", getContactById);

/**
 * @swagger
 * /api/contacts:
 *   post:
 *     summary: Create a new contact
 *     tags: [Contacts]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *        
 *             # The 'id' field is generated by the server and should NOT be sent by the client.
 *             $ref: '#/components/schemas/Contact'
 *     responses:
 *       201:
 *         description: The contact was successfully created (includes server-generated id)
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/Contact'
 *       400:
 *         description: Invalid input, object invalid, or missing required fields
 */
router.post("/contacts", createContact);

/**
 * @swagger
 * /api/contacts/{id}:
 *   put:
 *     summary: Update an existing contact
 *     tags: [Contacts]
 *     parameters:
 *       - in: path
 *         name: id
 *         schema:
 *           type: string
 *         required: true
 *         description: The contact ID to update
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/Contact' # Use updated schema name
 *     responses:
 *       200:
 *         description: The contact was updated successfully
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/Contact' # Use updated schema name
 *       400:
 *         description: Invalid input, no update data provided, or validation error
 *       404:
 *         description: Contact not found
 */

router.put("/contacts/:id", updateContact);

/**
 * @swagger
 * /api/contacts/{id}:
 *   delete:
 *     summary: Delete a contact
 *     tags: [Contacts]
 *     parameters:
 *       - in: path
 *         name: id
 *         schema:
 *           type: string
 *         required: true
 *         description: The contact ID to delete
 *     responses:
 *       200: # Or 204 No Content is also common for DELETE
 *         description: Contact deleted successfully
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 message:
 *                   type: string
 *                   example: Contact deleted successfully
 *       404:
 *         description: Contact not found
 *       500:
 *         description: Error deleting contact
 */

router.delete("/contacts/:id", deleteContact);

module.exports = router;